import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { MyNextUIProvider } from '@/app/providers/nextui-provider';
import { Toaster } from 'react-hot-toast';
import { ModalProvider } from '@/app/providers/modal-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyNextUIProvider>
          {children}
          <Toaster />
          <ModalProvider />
        </MyNextUIProvider>
      </body>
    </html>
  );
}
